{{- if .Values.cronJob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "horsing-around.fullname" . }}-purge-clients
  labels:
    {{- include "horsing-around.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: purge-clients
            image: mongo:latest
            command:
            - /bin/sh
            - -c
            - |
              mongosh "$MONGODB_URI" --eval 'db.clients.deleteMany({})'
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "horsing-around.fullname" . }}-secret
                  key: mongodb-uri
          restartPolicy: OnFailure
{{- end }}