apiVersion: v2
name: horsing-around
description: A Helm chart for Demo CRM application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mongodb
    version: "13.x.x"
    repository: "https://charts.bitnami.com/bitnami"